name: 'Install prerequisites'
description: 'Installs Brisk prerequisites'
    
runs:
  using: "composite"
  steps:
  - name: Install prerequisites (Linux)
    shell: bash
    if: ${{ runner.os == 'Linux' }}
    run: |
      sudo apt-get update && sudo apt-get install -y build-essential ninja-build cmake git
  - name: Install prerequisites (macOS)
    shell: bash
    if: ${{ runner.os == 'macOS' }}
    run: |
      brew install cmake git ninja
  - name: Install prerequisites (Windows)
    shell: powershell
    if: ${{ runner.os == 'Windows' }}
    run: |
      choco install ninja --no-progress -y
