name: 'Build using Visual Studio'
description: 'Builds app using Visual Studio'
inputs:
  triplet:
    description: 'Triplet'
    required: true
    
runs:
  using: "composite"
  steps:
  - name: Configure (Visual Studio)
    if: ${{ runner.os == 'Windows' }}
    shell: powershell
    run: >
      cmake -G"Visual Studio 17 2022" 
      -A ${{ startsWith(inputs.triplet, 'arm64-') && 'ARM64' || (startsWith(inputs.triplet, 'x64-') && 'x64' || 'Win32') }}
      -S example -B build_vs
      -DCMAKE_PREFIX_PATH=${{ github.workspace }}/dist/lib/cmake
      -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/deps/scripts/buildsystems/vcpkg.cmake
      -DVCPKG_INSTALLED_DIR=${{ github.workspace }}/deps/installed
      -DVCPKG_TARGET_TRIPLET=${{ inputs.triplet }}
      -DVCPKG_HOST_TRIPLET=${{(startsWith(inputs.triplet, 'arm64-') && runner.arch != 'ARM64' ) && 'x64-windows-static-md' || inputs.triplet}}
      -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>${{ endsWith(inputs.triplet, '-md') && 'DLL' || '' }}

  - name: Build (Visual Studio)
    if: ${{ runner.os == 'Windows' }}
    shell: powershell
    run: >
      cmake --build build_vs --config Release
