name: 'Build using Xcode'
description: 'Builds app using Xcode'
inputs:
  triplet:
    description: 'Triplet'
    required: true
  path-to-brisk:
    description: 'Brisk package directory'
    required: true
  path-to-vcpkg:
    description: 'Vcpkg directory'
    required: true
  path-to-installed:
    description: 'Vcpkg installed directory'
    required: true
    
runs:
  using: "composite"
  steps:
  - name: Configure (Xcode)
    if: ${{ runner.os == 'macOS' }}
    shell: bash
    run: >
      cmake -GXcode -S example -B build_xcode
      "-DCMAKE_PREFIX_PATH=${{ inputs.path-to-brisk }}/lib/cmake"
      "-DCMAKE_TOOLCHAIN_FILE=${{ inputs.path-to-vcpkg }}/scripts/buildsystems/vcpkg.cmake"
      "-DVCPKG_INSTALLED_DIR=${{ inputs.path-to-installed }}"
      -DCMAKE_OSX_ARCHITECTURES="${{ inputs.triplet == 'uni-osx' && 'x86_64;arm64' || (inputs.triplet == 'arm64-osx' && 'arm64' || 'x86_64') }}"
      -DVCPKG_TARGET_TRIPLET=${{ inputs.triplet }}
      -DVCPKG_HOST_TRIPLET=${{ inputs.triplet }}

  - name: Configure (Xcode)
    if: ${{ runner.os == 'macOS' }}
    shell: bash
    run: >
      cmake --build build_xcode --config Release
